server:
  port: 8000
spring:
  profiles:
    active: test
  application:
    name: microservice-provider-dx3906    # 项目名称尽量用小写
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:                           # 指定数据源
#    platform: h2                        # 指定数据源类型
#    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
#    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    top.hunaner.lol: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka    # 指定注册中心的地址
  instance:
    preferIpAddress: true
---
spring:
  profiles: development
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    top.hunaner.lol: DEBUG
---
spring:
  profiles: production
logging:
  level:
    root: warn
    org.hibernate: ware
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    org.hibernate.type.descriptor.sql.BasicExtractor: warn
    top.hunaner.lol: info
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:./test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /config/h2-console
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    top.hunaner.lol: DEBUG